baseURL: "https://kianorr.com/"
title: ~kian~
theme: PaperMod
paginate: 5
math:
  enable: true
enableInlineShortcodes: true



#defaultContentLanguage: en
#defaultContentLanguageInSubdir: false
disableLanguages:
 - se
languages:
  en:
    contentDir: content/english
    languageName: English
    weight: 1
    menu:
        main:
            - name: github
              url: "https://github.com/kianorr"
            - name: blog
              url: "./blog/"
            - name: cv
              url: "./cv"
  se:
    contentDir: content/swedish
    languageName: Svenska
    weight: 2

params:
  hideFooter: true
  ShowPostNavLinks: false
  ShowToc: true
  ShowBreadCrumbs: false
  assets:
    favicon: "/jupiter.png"

  socialIcons:
          - name: github
            url: "https://github.com/adityatelange/hugo-PaperMod"
  #homeInfoParams:
      #Title: "about me"
      #Content: Hello, my name is kian johan nils orr and this is my page! :) It features different areas of my life that I am passionate about, like physics research, books, or graphic design.
