baseURL = "https://kianorr.com/"
languageCode = "en-us"
title = "Kian"
theme = "cactus"

[params]

	colortheme = 'dark'
	mainSectionTitle = "Projects"
	mainSection = "posts"
	description = "hiiiiiiiiia;lkjd;lkaja;lkdj"
