baseURL: "https://kianorr.com/"
title: kian orr
theme: PaperMod
paginate: 5
math:
  enable: true
module:
  imports:
    - path: "github.com/gethugothemes/hugo-modules/gallery-slider"
# enableInlineShortcodes: true

#defaultContentLanguage: en
#defaultContentLanguageInSubdir: false
#disableLanguages:
# - se
cover:
  image: "../../sweden.jpg"
  relative: true
languages:
  en:
    contentDir: content/english
    languageName: English
    taxonomies:
      tag: "post-tags"
    weight: 1
    menu:
        main:
            - name: posts
              url: "./posts/"
              weight: 8
            - name: CV
              url: "./cv"
              weight: 9
            - name: ∫ research
              url: "./research"
              weight: 1
            - name: ❐ graphic design
              url: "./graphic-design"
              weight: 2
            - name: ❐ film photography
              url: "./film"
              weight: 3
                #- name: ✐ books
                #url: "./books"
                #weight: 3
    params:
      author: "kian orr"
      label:
            text: "kian orr"
            icon: "/earth.png"
      hideFooter: true
      ShowPostNavLinks: false
      ShowToc: true
      ShowBreadCrumbs: true
      plugins:
        css:
          - link: "plugins/glightbox/glightbox.css"
          - link: "plugins/swiper/swiper-bundle.css"
        js:
          - link: "plugins/glightbox/glightbox.js"
          - link: "js/gallery-slider.js"
          - link: "plugins/swiper/swiper-bundle.js"

      
      assets:
        favicon: "/jupiter.png"

      socialIcons:
              - name: github
                url: "https://github.com/kianorr"
      homeInfoParams:
          Title: "hello  (•◡•) /"
          Content: "my name is kian johan nils orr and this is my website! :) It features different areas of my life, like [physics research](/research), [books](/books), and [graphic design](/graphic-design). 
          I am currently in grad school, where I am beginning to do research in HED plasma physics. Below are some recent things I've done."
  sv:
    contentDir: content/swedish
    languageName: Swedish
    languageCode: sv
    taxonomies:
      tag: "post-tags"
    weight: 2
    #dateFormat: "Jan. 2, 2006"
    menu:
        main:
            - name: posts
              url: "./posts/"
              weight: 8
            - name: CV
              url: "./cv"
              weight: 9
            - name: ∫ research
              url: "./research"
              weight: 1
            - name: ❐ graphic design
              url: "./graphic-design"
              weight: 2
            - name: ✐ books
              url: "./books"
              weight: 3
    params:
      author: "kian orr"
      label:
            text: "kian orr"
            icon: "/earth.png"
      hideFooter: true
      ShowPostNavLinks: false
      ShowToc: true
      ShowBreadCrumbs: true
      
      assets:
        favicon: "/jupiter.png"

      socialIcons:
              - name: github
                url: "https://github.com/kianorr"
      homeInfoParams:
          Title: "hej  (•◡•) /"
          Content: Hej, jag heter kian johan nils orr och det här är min (svenka) sida! Det har olika områden av min liv, som fysik, böckar, och grafisk design.
