baseURL: "https://kianorr.com/"
languageCode: "en-us"
title: Kian
theme: PaperMod
paginate: 5
font: 'helvetica'

params:
  ShowToc: true
  ShowBreadCrumbs: true
  homeInfoParams:
      Title: "about me"
      Content: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eu volutpat neque. Curabitur iaculis lobortis rhoncus. Maecenas euismod lacus non nibh laoreet venenatis. Curabitur viverra, velit non porttitor semper, ipsum nunc imperdiet leo, ut interdum dolor est et leo. Nulla facilisi. Praesent id ex porttitor, rutrum elit ornare, sagittis felis. Nulla purus libero, scelerisque ac porta in, pharetra eu tortor. Morbi at felis mollis, maximus dolor sed, fermentum ligula. Curabitur molestie in purus ac varius. Nunc scelerisque nisl eros, bibendum consequat mauris dictum eget. Ut iaculis mi nec ipsum fringilla, at aliquam felis consectetur. Suspendisse id ligula tempus libero sagittis consequat. Aenean id tempus augue.
label:
  text: "j;lkajsdfl;akjf"