baseURL: "https://kianorr.com/"
title: kian orr
theme: PaperMod
paginate: 5
math:
  enable: true
enableInlineShortcodes: true


#defaultContentLanguage: en
#defaultContentLanguageInSubdir: false
disableLanguages:
 - se
languages:
  en:
    cover:
        image: "/sweden.jpg"
        relative: true
    contentDir: content/english
    languageName: English
    weight: 1
    menu:
        main:
            - name: posts
              url: "./blog/"
              weight: 8
            - name: CV
              url: "./cv"
              weight: 9
            - name: research
              url: "./research"
              weight: 1
            - name: graphic design
              url: "./graphic-design"
              weight: 2
            - name: books
              url: "./books"
              weight: 3
  se:
    contentDir: content/swedish
    languageName: Svenska
    weight: 2

params:
  images: "/sweden.jpg"
  label:
        text: "⌂ kian orr"
        # icon: "/favicon.png"
  hideFooter: true
  ShowPostNavLinks: false
  ShowToc: true
  ShowBreadCrumbs: true
  
  assets:
    favicon: "/jupiter.png"

  socialIcons:
          - name: github
            url: "https://github.com/kianorr"
  homeInfoParams:
      Title: "hello  (•◡•) /"
      Content: "my name is kian johan nils orr and this is my website! :) It features different areas of my life, like [physics research](/research), [books](/books), and [graphic design](/graphic-design). Below are some recent things I've done."
