baseURL = "https://kianorr.com/"
languageCode = "en-us"
title = "Kian"
theme = "cactus"

[params]

	colortheme = 'dark'
	mainSectionTitle = "Projects"
	mainSection = "posts"
	description = "helllloooo"
	tocInline = true
	tagsOverview = false
	dateFormat = ""

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

