baseURL: "https://kianorr.com/"
title: ~kian~
theme: PaperMod
paginate: 5
math:
  enable: true

defaultContentLanguage: en
defaultContentLanguageInSubdir: false
disableLanguages:
- se

languages:
  en:
    contentDir: content/english
    languageName: English
    weight: 1
  'se':
    contentDir: content/swedish
    languageName: Svenska
    weight: 2

params:
  cover:
    linkFullImages: true
    responsiveImages: true
  hideFooter: true
  ShowToc: true
  ShowBreadCrumbs: false
  homeInfoParams:
      Title: "about me"
      Content: Hello, my name is kian johan nils orr and this is my page! :) It features different areas of my life that I am passionate about, like physics research, books, or graphic design.

