baseURL: "https://kianorr.com/"
title: Kian Orr
theme: PaperMod
paginate: 5
math:
  enable: true
enableInlineShortcodes: true


#defaultContentLanguage: en
#defaultContentLanguageInSubdir: false
disableLanguages:
 - se
languages:
  en:
    cover:
        image: "/sweden.jpg"
        relative: true
    contentDir: content/english
    languageName: English
    weight: 1
    menu:
        main:
            - name: github
              url: "https://github.com/kianorr"
              weight: 10
            # - name: blog
              # url: "./blog/"
            - name: cv
              url: "./cv"
              weight: 9
            - name: research
              url: "./research"
              weight: 1
            - name: design
              url: "./graphic-design"
              weight: 2
            - name: books
              url: "./books"
              weight: 3
  se:
    contentDir: content/swedish
    languageName: Svenska
    weight: 2

params:
  images: "/sweden.jpg"
  label:
        text: "⌂ kian"
        # icon: "/sweden.jpg"
  hideFooter: true
  ShowPostNavLinks: false
  ShowToc: true
  ShowBreadCrumbs: false
  
  assets:
    favicon: "/jupiter.png"

  socialIcons:
          - name: github
            url: "https://github.com/adityatelange/hugo-PaperMod"
  # homeInfoParams:
      # Title: ""
      # Content: